project:
  type: website
  output-dir: docs
  
execute: 
  freeze: true 
  eval: true

website:
  title: mall
  favicon: "site/images/favicon/apple-touch-icon.png"
  navbar:
    logo: "site/images/favicon/apple-touch-icon.png"
    left:
      - sidebar:articles    
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/mlverse/mall    
  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Caching"
        href: articles/caching.qmd
      - text: "Performance"
        href: articles/performance.qmd                
      - text: "Databricks (R only)"
        href: articles/databricks.qmd        

format:
  html:
    toc: true
    toc-expand: true
    code-copy: true
    code-overflow: wrap
    code-toos: true
    eval: true
    freeze: true
    css: site/styles.css
    theme:
      light: [cosmo, site/theme.scss]
      dark: [cosmo, site/theme-dark.scss]

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"    
    
quartodoc:
  package: mall
  options: null
  style: pkgdown
  dir: reference
  out_index: _api_index.qmd
  dynamic: true
  sections:
    - title: Polars
      desc: ''
      contents:
      - name: MallFrame
    - title: Vectors
      desc: ''
      contents:
      - name: LLMVec


pkgsite: 
    dir: r
    reference:
      dir: reference
      template: site/_template_reference.qmd
      not_run_examples: true
      index:
        file: r_index.qmd
        template: site/_template_index.qmd
        contents:
          sections:
            - title: LLM
              contents: 
              - llm_classify
              - llm_custom
              - llm_extract
              - llm_sentiment
              - llm_summarize
              - llm_translate
              - llm_verify
              - llm_use
            - title: Data
              contents:               
              - reviews
